In [1]:
import numpy as np
import math

## Array Creation

In [2]:
a = np.array([1, 2, 3])
print(a)

print(a.ndim)

[1 2 3]
1


In [3]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
b.shape

(2, 3)

In [5]:
a.dtype

dtype('int64')

In [6]:
c = np.array([2.2, 5, 1.1])
c.dtype.name

'float64'

In [7]:
c

array([2.2, 5. , 1.1])

In [8]:
d = np.zeros((2,3))
print(d)

e = np.ones((2,3))
print(e)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
np.random.rand(2,3)

array([[0.059135  , 0.13597915, 0.71851365],
       [0.35051606, 0.64707785, 0.60555435]])

In [10]:
f = np.arange(10, 50, 2)
f

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [11]:
np.linspace(0, 2, 15)

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

## Array Operations

In [12]:
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

c = b-a
print(c)

d = a*b
print(d)

[ -9 -18 -27 -36]
[ 10  40  90 160]


In [13]:
farenheit = np.array([0, -10, -5, -15, 0])

celcius = (farenheit - 31) * (5/9)
celcius

array([-17.22222222, -22.77777778, -20.        , -25.55555556,
       -17.22222222])

In [14]:
celcius > -20

array([ True, False, False, False,  True])

In [15]:
celcius % 2 == 0

array([False, False,  True, False, False])

In [17]:
A = np.array([[1, 1], [0, 1]])
B = np.array([[2, 0], [3, 4]])

print(A*B)

# dot product
print(A@B)

[[2 0]
 [0 4]]
[[5 4]
 [3 4]]


In [18]:
A.shape

(2, 2)

In [19]:
arrayInt = np.array([[1, 2, 3], [4, 5, 6]])
print(arrayInt.dtype)

arrayFloat = np.array([[7.1, 8.1, 9.1], [10.1, 11.2, 12.3]])
print(arrayFloat.dtype)

int64
float64


In [20]:
array3 = arrayInt + arrayFloat
print(array3)
print(array3.dtype)

[[ 8.1 10.1 12.1]
 [14.1 16.2 18.3]]
float64


In [21]:
print(array3.sum())
print(array3.max())
print(array3.min())
print(array3.mean())

78.89999999999999
18.3
8.1
13.149999999999999


In [23]:
b = np.arange(1, 16, 1)
print(b)

b.reshape(3, 5)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [24]:
from PIL import Image
from IPython.display import display

im = Image.open('chris.tiff')
display(im)

FileNotFoundError: [Errno 2] No such file or directory: 'chris.tiff'